---
spring:
  profiles: default

server.port: 8443
server.ssl.key-store: localhost-keystore.p12
server.ssl.key-store-password: localhost
server.ssl.key-password: localhost

security.user.name : admin
security.user.password : secret
security.ignored: /index.html, /js/*.js, /img/apple-touch-icon.png, /Antonio-Light.ttf, /cache.manifest

ha:
  alarm:
    server-port : 8443
    read-timeout : 2000
    connect-timeout : 2000
    alarm-service-url : https://10.0.1.52:8443/alarm-panel
    keystore-file : localhost-keystore.p12
    keystore-pass : localhost
    allowed-ip: 127.0.0.4, 127.0.0.2, 127.0.0.3
    panel-host: localhost
    panel-port: 10000

logging.level.org.springframework.web: WARN
logging.level.spagnola.ha.alarm: DEBUG

---
spring:
   profiles: unit-test
ha:
   alarm:
      server-port : 8443
