---
spring:
  profiles: default

server.port: 9000

ha:
  alarm:
    server-port : 8443
    read-timeout : 10000
    connect-timeout : 10000
    username : admin
    password : YOUR_ZWAY_PASSWORD
    alarm-service-url : https://10.0.1.52:8443/alarm-panel
    keystore-file : keystore.p12
    keystore-pass : localhost
    allowed-ip: 
      - 127.0.0.1
      - 127.0.0.2
      - 127.0.0.3
    panel-host: localhost
    panel-port: 10000

logging.level.org.springframework.web: WARN
logging.level.spagnola.ha.alarm: DEBUG

---
spring:
   profiles: unit-test
ha:
   alarm:
      server-port : 8443
